export const industries = [
  "Please select one",
  "Agriculture and Forestry",
  "Arts, Entertainment, and Recreation",
  "Automotive",
  "Aviation & Aerospace",
  "Banking and Financial Services",
  "Biotechnology and Pharmaceuticals",
  "Broadcasting and Publishing",
  "Chemicals",
  "Computer Games and Internet",
  "Construction and Civil Engineering",
  "Consumer Goods",
  "Defense & Space",
  "Education",
  "Electrical/Electronic Manufacturing",
  "Energy, Oil and Renewables",
  "Facilities Services",
  "Farming, Fishing, and Hunting",
  "Food & Beverages",
  "Furniture",
  "Health Care and Social Assistance",
  "Hospitality",
  "Human Resources and Staffing",
  "Information Technology and Services",
  "Insurance",
  "Logistics and Supply Chain",
  "Management of Companies and Enterprises",
  "Manufacturing",
  "Maritime",
  "Medical Devices",
  "Mental Health Care",
  "Mining, Quarrying, and Oil and Gas Extraction",
  "Motion Pictures and Film",
  "Music",
  "Nanotechnology",
  "Outsourcing/Offshoring",
  "Packaging and Containers",
  "Professional, Scientific, and Technical Services",
  "Public Administration",
  "Real Estate and Rental and Leasing",
  "Research",
  "Retail",
  "Semiconductors",
  "Sports",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Transportation and Warehousing",
  "Utilities",
  "Veterinary",
  "Wholesale Trade",
  "Wireless",
]
