export const sectors = [
  "Please select one",
  "Agriculture",
  "Construction",
  "Consumer Discretionary",
  "Consumer Staples",
  "Education",
  "Energy",
  "Financials",
  "Healthcare",
  "Industrials",
  "Information Technology",
  "Materials",
  "Real Estate",
  "Telecommunication Services",
  "Utilities",
]
